# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reddit.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0creddit.proto\x12\x06reddit\"\x12\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\"\x88\x02\n\x04Post\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x13\n\timage_url\x18\x04 \x01(\tH\x00\x12\x13\n\tvideo_url\x18\x05 \x01(\tH\x00\x12\x14\n\x07user_id\x18\x06 \x01(\tH\x01\x88\x01\x01\x12\r\n\x05score\x18\x07 \x01(\x05\x12%\n\x05state\x18\x08 \x01(\x0e\x32\x16.reddit.Post.PostState\x12\x18\n\x10publication_date\x18\t \x01(\t\"/\n\tPostState\x12\n\n\x06NORMAL\x10\x00\x12\n\n\x06LOCKED\x10\x01\x12\n\n\x06HIDDEN\x10\x02\x42\x07\n\x05mediaB\n\n\x08_user_id\"\xb7\x01\n\x07\x43omment\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tparent_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\r\n\x05score\x18\x04 \x01(\x05\x12+\n\x05state\x18\x05 \x01(\x0e\x32\x1c.reddit.Comment.CommentState\x12\x18\n\x10publication_date\x18\x06 \x01(\t\"&\n\x0c\x43ommentState\x12\n\n\x06NORMAL\x10\x00\x12\n\n\x06HIDDEN\x10\x01\"#\n\x15GetTopCommentsRequest\x12\n\n\x02id\x18\x01 \x01(\t\"7\n\x1aRetrieveTopCommentsRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05limit\x18\x02 \x01(\x05\"@\n\x1bRetrieveTopCommentsResponse\x12!\n\x08\x63omments\x18\x01 \x03(\x0b\x32\x0f.reddit.Comment2\xbd\x03\n\rRedditService\x12(\n\nCreatePost\x12\x0c.reddit.Post\x1a\x0c.reddit.Post\x12(\n\nUpvotePost\x12\x0c.reddit.Post\x1a\x0c.reddit.Post\x12*\n\x0c\x44ownvotePost\x12\x0c.reddit.Post\x1a\x0c.reddit.Post\x12\x31\n\x13RetrievePostContent\x12\x0c.reddit.Post\x1a\x0c.reddit.Post\x12\x31\n\rCreateComment\x12\x0f.reddit.Comment\x1a\x0f.reddit.Comment\x12\x31\n\rUpvoteComment\x12\x0f.reddit.Comment\x1a\x0f.reddit.Comment\x12\x33\n\x0f\x44ownvoteComment\x12\x0f.reddit.Comment\x1a\x0f.reddit.Comment\x12^\n\x13RetrieveTopComments\x12\".reddit.RetrieveTopCommentsRequest\x1a#.reddit.RetrieveTopCommentsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reddit_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USER']._serialized_start=24
  _globals['_USER']._serialized_end=42
  _globals['_POST']._serialized_start=45
  _globals['_POST']._serialized_end=309
  _globals['_POST_POSTSTATE']._serialized_start=241
  _globals['_POST_POSTSTATE']._serialized_end=288
  _globals['_COMMENT']._serialized_start=312
  _globals['_COMMENT']._serialized_end=495
  _globals['_COMMENT_COMMENTSTATE']._serialized_start=457
  _globals['_COMMENT_COMMENTSTATE']._serialized_end=495
  _globals['_GETTOPCOMMENTSREQUEST']._serialized_start=497
  _globals['_GETTOPCOMMENTSREQUEST']._serialized_end=532
  _globals['_RETRIEVETOPCOMMENTSREQUEST']._serialized_start=534
  _globals['_RETRIEVETOPCOMMENTSREQUEST']._serialized_end=589
  _globals['_RETRIEVETOPCOMMENTSRESPONSE']._serialized_start=591
  _globals['_RETRIEVETOPCOMMENTSRESPONSE']._serialized_end=655
  _globals['_REDDITSERVICE']._serialized_start=658
  _globals['_REDDITSERVICE']._serialized_end=1103
# @@protoc_insertion_point(module_scope)
